### ISSUE TITLE
(MacOS) Option key as Meta key

### ISSUE THREAD

**Issue by CyberneticSquid** [GitSquared/edex-ui#759]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [x] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Add a setting to use the option key for "meta", like Terminal.app's "Use Option key as Meta key" setting. Could be pretty helpful for using programs like `emacs` or `nano`

**Comment by GitSquared** [comment]
You mean with the touch keyboard? This could probably be handled with a custom keyboard layout.
